# <center>Upgrad Capstone</center>
#### <center>`Project facilitator: Prashant Bhide`&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`Project partner: Anilkumar Narayanam`</center>

## Subtask 5 - Model Building - Data Segmentation

In [1]:
# Importing the required libraries

import warnings
import numpy as np
import pandas as pd

In [2]:
# Global configurations

warnings.filterwarnings('ignore')

pd.set_option('display.float_format', '{:.2f}'.format)
pd.options.display.max_colwidth = 100

### Encoding the Data

In [3]:
%%time
# We will read the master dataset from earlier stage

df_master = pd.read_csv('df_master.csv', dtype={'device_id':str, 'age':np.int8, 'event_id':str})
display(df_master)
df_master.info()

,device_id,gender,age,event_id,hour,dayofweek,avg_events,cluster_id,is_active,gaming,...,family,children,education,lifestyle,social,services,others,phone_brand,device_model,train_test_flag
0,-1000369272589010000,F,26,NaN,nan,NaN,0,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,vivo,Y17T,test
1,-1000572055892390000,F,27,NaN,nan,NaN,0,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,OPPO,R819T,train
2,-1000643208750510000,M,29,NaN,nan,NaN,0,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,Gionee,GN137,train
3,-1001337759327040000,M,30,2774404,9.00,6-Sat,109,0.00,21.00,0.00,...,1.00,0.00,1.00,1.00,1.00,1.00,1.00,OPPO,A31,train
4,-1001337759327040000,M,30,3065018,10.00,3-Wed,109,0.00,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,OPPO,A31,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1266928,99976251796408100,M,43,839154,8.00,6-Sat,3,nan,13.00,0.00,...,1.00,0.00,1.00,1.00,1.00,1.00,1.00,others,Touch 2,test
1266929,99976251796408100,M,43,2642482,8.00,6-Sat,3,nan,11.00,0.00,...,1.00,0.00,1.00,1.00,1.00,1.00,1.00,others,Touch 2,test
1266930,99976251796408100,M,43,2642573,8.00,6-Sat,3,nan,13.00,0.00,...,1.00,0.00,1.00,1.00,1.00,1.00,1.00,others,Touch 2,test
1266931,999861742187156000,M,27,NaN,nan,NaN,0,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,Xiaomi,MI 2S,train
1266932,999942881634637000,F,31,NaN,nan,NaN,0,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,samsung,Galaxy Note 2,train

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1266933 entries, 0 to 1266932
Data columns (total 23 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   device_id        1266933 non-null  object
 1   gender           1266933 non-null  object
 2   age              1266933 non-null  int8
 3   event_id         1215598 non-null  object
 4   hour             1215598 non-null  float64
 5   dayofweek        1215598 non-null  object
 6   avg_events       1266933 non-null  int64
 7   cluster_id       829077 non-null   float64
 8   is_active        556378 non-null   float64
 9   gaming           556378 non-null   float64
 10  financial        556378 non-null   float64
 11  travel           556378 non-null   float64
 12  technology       556378 non-null   float64
 13  family           556378 non-null   float64
 14  children         556378 non-null   float64
 15  education        556378 non-null   float64
 16  lifestyle        556378 non-null   float64
 17  social           556378 non-null   float64
 18  services         556378 non-null   float64
 19  others           556378 non-null   float64
 20  phone_brand      1266933 non-null  object
 21  device_model     1266933 non-null  object
 22  train_test_flag  1266933 non-null  object
dtypes: float64(14), int64(1), int8(1), object(7)
memory usage: 213.9+ MB
Wall time: 4.57 s

___We will use the following encoding for the gender and age class predictions:<br>
Gender : 'F'=0 and 'M'=1<br>
Age Group : [0-24]=0, [25-32]=1, [32+]=2___

In [4]:
%%time
# We will map / encode the train flag and target class columns

df_master['gender'] = df_master['gender'].map({'F':0, 'M':1})
df_master['gender'] = df_master['gender'].astype('category')

df_master['age'] = pd.cut(df_master['age'], bins=[0, 24, 32, 100], labels=[0, 1, 2])

df_master['train_test_flag'] = df_master['train_test_flag'].astype('category')

df_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1266933 entries, 0 to 1266932
Data columns (total 23 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   device_id        1266933 non-null  object
 1   gender           1266933 non-null  category
 2   age              1266933 non-null  category
 3   event_id         1215598 non-null  object
 4   hour             1215598 non-null  float64
 5   dayofweek        1215598 non-null  object
 6   avg_events       1266933 non-null  int64
 7   cluster_id       829077 non-null   float64
 8   is_active        556378 non-null   float64
 9   gaming           556378 non-null   float64
 10  financial        556378 non-null   float64
 11  travel           556378 non-null   float64
 12  technology       556378 non-null   float64
 13  family           556378 non-null   float64
 14  children         556378 non-null   float64
 15  education        556378 non-null   float64
 16  lifestyle        556378 non-null   float64
 17  social           556378 non-null   float64
 18  services         556378 non-null   float64
 19  others           556378 non-null   float64
 20  phone_brand      1266933 non-null  object
 21  device_model     1266933 non-null  object
 22  train_test_flag  1266933 non-null  category
dtypes: category(3), float64(14), int64(1), object(5)
memory usage: 196.9+ MB
Wall time: 725 ms

In [5]:
%%time
# We will create dummy features (one-hot encoded) for the common (to both Scenario1 & Scenario2) categorical variables

common_categorical_cols = ['phone_brand', 'device_model']
df_master[common_categorical_cols] = df_master[common_categorical_cols].astype('category')
dummy1 = pd.get_dummies(df_master[common_categorical_cols], drop_first=False)

# Adding the results to the master dataframe
df_master = pd.concat([df_master, dummy1], axis=1).drop(columns=common_categorical_cols)
display(df_master)
df_master.info()
del common_categorical_cols, dummy1

,device_id,gender,age,event_id,hour,dayofweek,avg_events,cluster_id,is_active,gaming,...,device_model_é­…è“2,device_model_é­…è“metal,device_model_éº¦èŠ’3,device_model_éº¦èŠ’3S,device_model_éº¦èŠ’4,device_model_é»„é‡‘æ–—å£«A8,device_model_é»„é‡‘æ–—å£«Note8,device_model_é”‹å°š,device_model_é”‹å°šPro,device_model_é‡‘é’¢
0,-1000369272589010000,0,1,NaN,nan,NaN,0,nan,nan,nan,...,0,0,0,0,0,0,0,0,0,0
1,-1000572055892390000,0,1,NaN,nan,NaN,0,nan,nan,nan,...,0,0,0,0,0,0,0,0,0,0
2,-1000643208750510000,1,1,NaN,nan,NaN,0,nan,nan,nan,...,0,0,0,0,0,0,0,0,0,0
3,-1001337759327040000,1,1,2774404,9.00,6-Sat,109,0.00,21.00,0.00,...,0,0,0,0,0,0,0,0,0,0
4,-1001337759327040000,1,1,3065018,10.00,3-Wed,109,0.00,nan,nan,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1266928,99976251796408100,1,2,839154,8.00,6-Sat,3,nan,13.00,0.00,...,0,0,0,0,0,0,0,0,0,0
1266929,99976251796408100,1,2,2642482,8.00,6-Sat,3,nan,11.00,0.00,...,0,0,0,0,0,0,0,0,0,0
1266930,99976251796408100,1,2,2642573,8.00,6-Sat,3,nan,13.00,0.00,...,0,0,0,0,0,0,0,0,0,0
1266931,999861742187156000,1,1,NaN,nan,NaN,0,nan,nan,nan,...,0,0,0,0,0,0,0,0,0,0
1266932,999942881634637000,0,1,NaN,nan,NaN,0,nan,nan,nan,...,0,0,0,0,0,0,0,0,0,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1266933 entries, 0 to 1266932
Columns: 543 entries, device_id to device_model_é‡‘é’¢
dtypes: category(3), float64(14), int64(1), object(3), uint8(522)
memory usage: 808.3+ MB
Wall time: 10.1 s

### Segmenting the Data

#### Scenario 1 - All the data present (i.e. latitude-longitude data, application id data, event data and devices data)

In [6]:
%%time
# We will separate out the scenario 1 data from the master dataset

df_scn1 = df_master.copy().dropna()
display(df_scn1)
df_scn1.info()

,device_id,gender,age,event_id,hour,dayofweek,avg_events,cluster_id,is_active,gaming,...,device_model_é­…è“2,device_model_é­…è“metal,device_model_éº¦èŠ’3,device_model_éº¦èŠ’3S,device_model_éº¦èŠ’4,device_model_é»„é‡‘æ–—å£«A8,device_model_é»„é‡‘æ–—å£«Note8,device_model_é”‹å°š,device_model_é”‹å°šPro,device_model_é‡‘é’¢
3,-1001337759327040000,1,1,2774404,9.00,6-Sat,109,0.00,21.00,0.00,...,0,0,0,0,0,0,0,0,0,0
6,-1001337759327040000,1,1,2906128,10.00,6-Sat,109,0.00,48.00,0.00,...,0,0,0,0,0,0,0,0,0,0
7,-1001337759327040000,1,1,2876843,10.00,6-Sat,109,0.00,22.00,0.00,...,0,0,0,0,0,0,0,0,0,0
10,-1001337759327040000,1,1,3141167,9.00,6-Sat,109,0.00,40.00,0.00,...,0,0,0,0,0,0,0,0,0,0
12,-1001337759327040000,1,1,2647428,9.00,6-Sat,109,0.00,40.00,0.00,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1266912,999208698621622000,1,1,2892952,22.00,6-Sat,37,39.00,5.00,0.00,...,0,0,0,0,0,0,0,0,0,0
1266915,999208698621622000,1,1,2892302,22.00,3-Wed,37,39.00,16.00,0.00,...,0,0,0,0,0,0,0,0,0,0
1266919,999208698621622000,1,1,27998,23.00,1-Mon,37,39.00,8.00,0.00,...,0,0,0,0,0,0,0,0,0,0
1266920,999208698621622000,1,1,603552,12.00,2-Tue,37,39.00,8.00,0.00,...,0,0,0,0,0,0,0,0,0,0
1266923,999208698621622000,1,1,455299,16.00,7-Sun,37,39.00,3.00,0.00,...,0,0,0,0,0,0,0,0,0,0

<class 'pandas.core.frame.DataFrame'>
Int64Index: 193199 entries, 3 to 1266923
Columns: 543 entries, device_id to device_model_é‡‘é’¢
dtypes: category(3), float64(14), int64(1), object(3), uint8(522)
memory usage: 124.7+ MB
Wall time: 3.23 s

In [7]:
%%time
# We will create dummy features (one-hot encoded) for the Scenario1 specific categorical variables

scn1_categorical_cols = ['hour', 'dayofweek', 'cluster_id']
df_scn1[scn1_categorical_cols] = df_scn1[scn1_categorical_cols].astype('category')
dummy1 = pd.get_dummies(df_scn1[scn1_categorical_cols], drop_first=False)

# Adding the results to the master dataframe
df_scn1 = pd.concat([df_scn1, dummy1], axis=1).drop(columns=scn1_categorical_cols)
display(df_scn1)
df_scn1.info()
del scn1_categorical_cols, dummy1

,device_id,gender,age,event_id,avg_events,is_active,gaming,financial,travel,technology,...,cluster_id_116.0,cluster_id_117.0,cluster_id_118.0,cluster_id_119.0,cluster_id_120.0,cluster_id_121.0,cluster_id_122.0,cluster_id_123.0,cluster_id_124.0,cluster_id_125.0
3,-1001337759327040000,1,1,2774404,109,21.00,0.00,1.00,1.00,1.00,...,0,0,0,0,0,0,0,0,0,0
6,-1001337759327040000,1,1,2906128,109,48.00,0.00,1.00,1.00,1.00,...,0,0,0,0,0,0,0,0,0,0
7,-1001337759327040000,1,1,2876843,109,22.00,0.00,1.00,1.00,1.00,...,0,0,0,0,0,0,0,0,0,0
10,-1001337759327040000,1,1,3141167,109,40.00,0.00,1.00,1.00,1.00,...,0,0,0,0,0,0,0,0,0,0
12,-1001337759327040000,1,1,2647428,109,40.00,0.00,1.00,1.00,1.00,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1266912,999208698621622000,1,1,2892952,37,5.00,0.00,1.00,1.00,1.00,...,0,0,0,0,0,0,0,0,0,0
1266915,999208698621622000,1,1,2892302,37,16.00,0.00,1.00,1.00,1.00,...,0,0,0,0,0,0,0,0,0,0
1266919,999208698621622000,1,1,27998,37,8.00,0.00,1.00,1.00,1.00,...,0,0,0,0,0,0,0,0,0,0
1266920,999208698621622000,1,1,603552,37,8.00,0.00,1.00,0.00,0.00,...,0,0,0,0,0,0,0,0,0,0
1266923,999208698621622000,1,1,455299,37,3.00,0.00,1.00,1.00,1.00,...,0,0,0,0,0,0,0,0,0,0

<class 'pandas.core.frame.DataFrame'>
Int64Index: 193199 entries, 3 to 1266923
Columns: 698 entries, device_id to cluster_id_125.0
dtypes: category(3), float64(12), int64(1), object(2), uint8(680)
memory usage: 149.4+ MB
Wall time: 798 ms

In [8]:
# We will prepare the various columns to be aggregated over groupby 'device_id' column

all_cols = list(df_scn1.columns)
cols_to_keep_first = ['gender', 'age', 'avg_events', 'train_test_flag']
cols_to_sum_up = ['is_active', 'gaming', 'financial', 'travel', 'technology', 'family',
                  'children', 'education', 'lifestyle','social','services','others']

for col in all_cols:
    if (col.startswith('phone_brand') or col.startswith('device_model')):
        cols_to_keep_first.append(col)
    if (col.startswith('hour') or col.startswith('dayofweek') or col.startswith('cluster_id')):
        cols_to_sum_up.append(col)

print('cols_to_keep_first =', cols_to_keep_first)
print('cols_to_sum_up =', cols_to_sum_up)
del all_cols

cols_to_keep_first = ['gender', 'age', 'avg_events', 'train_test_flag', 'phone_brand_Coolpad', 'phone_brand_Gionee', 'phone_brand_HTC', 'phone_brand_Huawei', 'phone_brand_LG', 'phone_brand_Meizu', 'phone_brand_OPPO', 'phone_brand_Sony', 'phone_brand_TCL', 'phone_brand_Xiaomi', 'phone_brand_ZTE', 'phone_brand_ccmc', 'phone_brand_dowe', 'phone_brand_hisense', 'phone_brand_lenovo', 'phone_brand_lshi', 'phone_brand_nubia', 'phone_brand_others', 'phone_brand_samsung', 'phone_brand_vivo', 'phone_brand_youmi', 'device_model_1105', 'device_model_1107', 'device_model_2', 'device_model_2016GalAxyA7', 'device_model_2016GalAxyA9', 'device_model_3', 'device_model_3007', 'device_model_45rggt2', 'device_model_5263', 'device_model_5890', 'device_model_5891', 'device_model_5891Q', 'device_model_5892', 'device_model_5950', 'device_model_5951', 'device_model_6607', 'device_model_7269', 'device_model_7270', 'device_model_7295', 'device_model_7295+', 'device_model_7295A123', 'device_model_7295C', 'device_model_7296', 'device_model_7620l', 'device_model_795+', 'device_model_8017-T00', 'device_model_802w', 'device_model_8085', 'device_model_8089', 'device_model_8190Q', 'device_model_8198T', 'device_model_8702', 'device_model_8705', 'device_model_8712', 'device_model_8720', 'device_model_8720L', 'device_model_8729', 'device_model_8730L', 'device_model_900tr2', 'device_model_900tr212', 'device_model_900tr2123', 'device_model_9180', 'device_model_9190l', 'device_model_9976A', 'device_model_:UOOGOUT1', 'device_model_A1', 'device_model_A11', 'device_model_A199', 'device_model_A2800d', 'device_model_A3000-H', 'device_model_A31', 'device_model_A320t', 'device_model_A33', 'device_model_A355e', 'device_model_A360t', 'device_model_A3800d', 'device_model_A388t', 'device_model_A3900', 'device_model_A390t', 'device_model_A51', 'device_model_A53', 'device_model_A5800-D', 'device_model_A628t', 'device_model_A630t', 'device_model_A670t', 'device_model_A680', 'device_model_A708t', 'device_model_A788t', 'device_model_A789', 'device_model_A800', 'device_model_A820', 'device_model_A820t', 'device_model_A830', 'device_model_A850', 'device_model_A858t', 'device_model_A880', 'device_model_A890e', 'device_model_Ascend G6', 'device_model_Ascend G7', 'device_model_Ascend G700', 'device_model_Ascend G700T', 'device_model_Ascend GX1', 'device_model_Ascend P6', 'device_model_Ascend P7', 'device_model_Ascend P8', 'device_model_B199', 'device_model_B9388', 'device_model_Butterfly', 'device_model_C8813', 'device_model_C8813Q', 'device_model_C8815', 'device_model_C8816', 'device_model_C8816D', 'device_model_C8817E', 'device_model_C8818', 'device_model_Desire 626', 'device_model_Desire 816', 'device_model_Desire 820', 'device_model_Desire 826', 'device_model_E3', 'device_model_E5', 'device_model_E6', 'device_model_E7', 'device_model_ELIFE E3T', 'device_model_ELIFE S5.5', 'device_model_F103', 'device_model_F2', 'device_model_F301', 'device_model_F303', 'device_model_Find 5', 'device_model_Find 7', 'device_model_G11', 'device_model_G2', 'device_model_G3', 'device_model_G3588V', 'device_model_G3818', 'device_model_G510', 'device_model_G520-0000', 'device_model_G520-5000', 'device_model_G520-T10', 'device_model_G6-C00', 'device_model_G6-U00', 'device_model_G606', 'device_model_G610C', 'device_model_G610S', 'device_model_G610T', 'device_model_G620-L75', 'device_model_G628', 'device_model_G660-L075', 'device_model_G7 Plus', 'device_model_G716', 'device_model_G718C', 'device_model_G7200', 'device_model_G730-T00', 'device_model_G730-U00', 'device_model_G750-T20', 'device_model_GN137', 'device_model_GN151', 'device_model_GN706L', 'device_model_GN708W', 'device_model_GN9002', 'device_model_Galaxy A3', 'device_model_Galaxy A5', 'device_model_Galaxy A7', 'device_model_Galaxy A8', 'device_model_Galaxy Ace', 'device_model_Galaxy Ace 2', 'device_model_Galaxy Ace 3', 'device_model_Galaxy Core 2', 'device_model_Galaxy Core 4G', 'device_model_Galaxy Core Max', 'device_model_Galaxy Core Mini', 'device_model_Galaxy Core Prime', 'device_model_Galaxy E7', 'device_model_Galaxy Fame', 'device_model_Galaxy Grand', 'device_model_Galaxy Grand 2', 'device_model_Galaxy Grand DUOS', 'device_model_Galaxy Grand Neo Plus', 'device_model_Galaxy Grand Prime', 'device_model_Galaxy J3', 'device_model_Galaxy J5', 'device_model_Galaxy J7', 'device_model_Galaxy Mega 2', 'device_model_Galaxy Mega 5.8', 'device_model_Galaxy Mega 6.3', 'device_model_Galaxy Mega Plus', 'device_model_Galaxy Nexus', 'device_model_Galaxy Note', 'device_model_Galaxy Note 2', 'device_model_Galaxy Note 3', 'device_model_Galaxy Note 3 Lite', 'device_model_Galaxy Note 4', 'device_model_Galaxy Note 5', 'device_model_Galaxy Note 8.0', 'device_model_Galaxy Note Edge', 'device_model_Galaxy On5', 'device_model_Galaxy On7', 'device_model_Galaxy Premier', 'device_model_Galaxy S2', 'device_model_Galaxy S2 HD LTE E120S', 'device_model_Galaxy S2 Plus', 'device_model_Galaxy S3', 'device_model_Galaxy S3 Neo+', 'device_model_Galaxy S4', 'device_model_Galaxy S4 Zoom', 'device_model_Galaxy S5', 'device_model_Galaxy S6', 'device_model_Galaxy S6 Edge', 'device_model_Galaxy S6 Edge+', 'device_model_Galaxy Style DUOS', 'device_model_Galaxy Tab 2 P3100', 'device_model_Galaxy Tab 3 10.1', 'device_model_Galaxy Tab 3 7.0', 'device_model_Galaxy Tab 3 8.0', 'device_model_Galaxy Trend 2', 'device_model_Galaxy Trend 3', 'device_model_Galaxy Trend DUOS', 'device_model_Galaxy Trend DUOS 2', 'device_model_Galaxy Win', 'device_model_Galaxy Win Pro', 'device_model_Grand Memo 2', 'device_model_Grand S 2', 'device_model_Grand X Quad', 'device_model_HN3-U01', 'device_model_HT-I860', 'device_model_I8268', 'device_model_I9118', 'device_model_K1', 'device_model_K860i', 'device_model_K900', 'device_model_L1 mini', 'device_model_M032', 'device_model_M2', 'device_model_M20-T', 'device_model_M310', 'device_model_M4', 'device_model_M5', 'device_model_M811', 'device_model_M812C', 'device_model_M8St', 'device_model_MI 1S', 'device_model_MI 2', 'device_model_MI 2A', 'device_model_MI 2C', 'device_model_MI 2S', 'device_model_MI 3', 'device_model_MI 4', 'device_model_MI 5', 'device_model_MI One C1', 'device_model_MI One Plus', 'device_model_MI pad', 'device_model_MT1-U06', 'device_model_MT2-C00', 'device_model_MX2', 'device_model_MX3', 'device_model_MX4', 'device_model_MX4 Pro', 'device_model_MX5', 'device_model_Mate', 'device_model_Mate 2', 'device_model_Mate 7', 'device_model_Mate 8', 'device_model_Mate S', 'device_model_Moto G', 'device_model_Moto X', 'device_model_N1', 'device_model_N1 Mini', 'device_model_N1T', 'device_model_N3', 'device_model_Nexus 4', 'device_model_Nexus 5', 'device_model_One', 'device_model_One E8', 'device_model_One M8', 'device_model_One X', 'device_model_One max', 'device_model_Optimus G Pro', 'device_model_P301M', 'device_model_P6', 'device_model_P70', 'device_model_P770', 'device_model_P8 Lite', 'device_model_P880', 'device_model_P8max', 'device_model_PRO5', 'device_model_Q505T', 'device_model_Q802T', 'device_model_R1', 'device_model_R1C', 'device_model_R1S', 'device_model_R2017', 'device_model_R3', 'device_model_R5', 'device_model_R6007', 'device_model_R7', 'device_model_R7 Plus', 'device_model_R7s', 'device_model_R809T', 'device_model_R811', 'device_model_R813T', 'device_model_R815T', 'device_model_R817T', 'device_model_R819T', 'device_model_R8205', 'device_model_R821T', 'device_model_R823T', 'device_model_R827T', 'device_model_R830', 'device_model_R831S', 'device_model_R831T', 'device_model_R833T', 'device_model_S2y', 'device_model_S3', 'device_model_S5.1', 'device_model_S5.5L', 'device_model_S5830I', 'device_model_S6', 'device_model_S658t', 'device_model_S7', 'device_model_S720', 'device_model_S7568', 'device_model_S7568I', 'device_model_S7898', 'device_model_S7I', 'device_model_S7T', 'device_model_S810t', 'device_model_S820', 'device_model_S850t', 'device_model_S868t', 'device_model_S890', 'device_model_S898t', 'device_model_S9', 'device_model_S90-t', 'device_model_S920', 'device_model_T1', 'device_model_T329t', 'device_model_Talkv2', 'device_model_Touch 2', 'device_model_Touch 3', 'device_model_Two', 'device_model_U3', 'device_model_U51GT-W', 'device_model_U705T', 'device_model_U707T', 'device_model_U807', 'device_model_U817', 'device_model_U9508', 'device_model_U956', 'device_model_UIMI3', 'device_model_UIMI4', 'device_model_V182', 'device_model_V185', 'device_model_V5 Max', 'device_model_V5S', 'device_model_V967S', 'device_model_VIBE X2', 'device_model_VIBE Z', 'device_model_W2013', 'device_model_W2014', 'device_model_W2015', 'device_model_X1', 'device_model_X1 7.0', 'device_model_X1ST', 'device_model_X3L', 'device_model_X3S', 'device_model_X3T', 'device_model_X3V', 'device_model_X5L', 'device_model_X5M', 'device_model_X5Max', 'device_model_X5Max+', 'device_model_X5Pro', 'device_model_X5SL', 'device_model_X5V', 'device_model_X6', 'device_model_X6 D', 'device_model_X6 L', 'device_model_X6 Plus', 'device_model_X6 Plus D', 'device_model_X710L', 'device_model_X805', 'device_model_X907', 'device_model_XL', 'device_model_Xperia C', 'device_model_Xperia C3', 'device_model_Xperia P', 'device_model_Xperia S', 'device_model_Xperia SL', 'device_model_Xperia SP', 'device_model_Xperia T2 Ultra', 'device_model_Xperia TX', 'device_model_Xperia Z', 'device_model_Xperia Z Ultra', 'device_model_Xperia Z1', 'device_model_Xperia Z2', 'device_model_Xperia Z3', 'device_model_Xperia arc S', 'device_model_Xplay', 'device_model_Xplay3S', 'device_model_Y11', 'device_model_Y11IT', 'device_model_Y11IW', 'device_model_Y13', 'device_model_Y13L', 'device_model_Y13iL', 'device_model_Y15', 'device_model_Y17T', 'device_model_Y17W', 'device_model_Y18L', 'device_model_Y19T', 'device_model_Y20T', 'device_model_Y22', 'device_model_Y22IL', 'device_model_Y22L', 'device_model_Y23L', 'device_model_Y27', 'device_model_Y28L', 'device_model_Y29L', 'device_model_Y300', 'device_model_Y33', 'device_model_Y35', 'device_model_Y37', 'device_model_Y51', 'device_model_Y511-T00', 'device_model_Y511-U00', 'device_model_Y516', 'device_model_Y600-U00', 'device_model_Y613', 'device_model_Y635', 'device_model_Y635-TL00', 'device_model_Y80D', 'device_model_Y913', 'device_model_Y923', 'device_model_Y927', 'device_model_Z1', 'device_model_Z5S', 'device_model_Z5S Mini', 'device_model_Z7 Max', 'device_model_Z7 Mini', 'device_model_Z9', 'device_model_Z9 Max', 'device_model_Z9 mini', 'device_model_ZenFone 2', 'device_model_a1900tr212', 'device_model_bigv23', 'device_model_cv1', 'device_model_cv1plus', 'device_model_hu1', 'device_model_hu1 Plus', 'device_model_hu1 plus', 'device_model_iPh-800', 'device_model_iSuper S1', 'device_model_ihv1', 'device_model_ivvi K1 mini', 'device_model_ivvi å°\x8fi', 'device_model_mate7es2', 'device_model_menote1', 'device_model_menote1 2', 'device_model_notev123', 'device_model_others', 'device_model_x1', 'device_model_x11S', 'device_model_x12', 'device_model_x12A', 'device_model_x13', 'device_model_xnote', 'device_model_xnote11', 'device_model_xnote2', 'device_model_xnote3', 'device_model_xnotea11', 'device_model_zt_121', 'device_model_ä¹\x90æª¬K3', 'device_model_ä¹\x90æª¬K3 Note', 'device_model_ä¹ˆä¹ˆå“’', 'device_model_ä¹ˆä¹ˆå“’3N', 'device_model_å\x9dšæžœæ‰‹æœº', 'device_model_å°\x8fç±³4C', 'device_model_å°\x8fè¾£æ¤’ M2', 'device_model_å°\x8fè‹¹æžœ', 'device_model_æ˜¥é›·HD', 'device_model_æ˜Ÿæ˜Ÿ1å\x8f·', 'device_model_æ——èˆ°ç‰ˆ', 'device_model_ç\x81«æ˜Ÿä¸€å\x8f·', 'device_model_çº¢è¾£æ¤’', 'device_model_çº¢è¾£æ¤’Note', 'device_model_çº½æ‰£', 'device_model_ç‚«å½±S+', 'device_model_ç•…äº«5', 'device_model_ç•…äº«5S', 'device_model_è\x81”æƒ³é»„é‡‘æ–—å£«S8', 'device_model_è\x8d£è€€+', 'device_model_è\x8d£è€€3C', 'device_model_è\x8d£è€€3Cç•…çŽ©ç‰ˆ', 'device_model_è\x8d£è€€3X', 'device_model_è\x8d£è€€3Xç•…çŽ©ç‰ˆ', 'device_model_è\x8d£è€€4A', 'device_model_è\x8d£è€€7', 'device_model_è\x8d£è€€7i', 'device_model_è\x8d£è€€X2', 'device_model_è\x8d£è€€ç•…çŽ©4', 'device_model_è\x8d£è€€ç•…çŽ©4C', 'device_model_è\x8d£è€€ç•…çŽ©4Cè¿\x90åŠ¨ç‰ˆ', 'device_model_è\x8d£è€€ç•…çŽ©4X', 'device_model_è\x8d£è€€ç•…çŽ©5', 'device_model_è\x8d£è€€ç•…çŽ©5X', 'device_model_è¶…çº§æ‰‹æœº1', 'device_model_è¶…çº§æ‰‹æœº1 Pro', 'device_model_è¶…çº§æ‰‹æœºMax', 'device_model_é\x9d’æ˜¥ç‰ˆ', 'device_model_é\xad…è“\x9d', 'device_model_é\xad…è“\x9d2', 'device_model_é\xad…è“\x9dmetal', 'device_model_éº¦èŠ’3', 'device_model_éº¦èŠ’3S', 'device_model_éº¦èŠ’4', 'device_model_é»„é‡‘æ–—å£«A8', 'device_model_é»„é‡‘æ–—å£«Note8', 'device_model_é”‹å°š', 'device_model_é”‹å°šPro', 'device_model_é‡‘é’¢']
cols_to_sum_up = ['is_active', 'gaming', 'financial', 'travel', 'technology', 'family', 'children', 'education', 'lifestyle', 'social', 'services', 'others', 'hour_0.0', 'hour_1.0', 'hour_2.0', 'hour_3.0', 'hour_4.0', 'hour_5.0', 'hour_6.0', 'hour_7.0', 'hour_8.0', 'hour_9.0', 'hour_10.0', 'hour_11.0', 'hour_12.0', 'hour_13.0', 'hour_14.0', 'hour_15.0', 'hour_16.0', 'hour_17.0', 'hour_18.0', 'hour_19.0', 'hour_20.0', 'hour_21.0', 'hour_22.0', 'hour_23.0', 'dayofweek_1-Mon', 'dayofweek_2-Tue', 'dayofweek_3-Wed', 'dayofweek_4-Thu', 'dayofweek_5-Fri', 'dayofweek_6-Sat', 'dayofweek_7-Sun', 'cluster_id_-1.0', 'cluster_id_0.0', 'cluster_id_1.0', 'cluster_id_2.0', 'cluster_id_3.0', 'cluster_id_4.0', 'cluster_id_5.0', 'cluster_id_6.0', 'cluster_id_7.0', 'cluster_id_8.0', 'cluster_id_9.0', 'cluster_id_10.0', 'cluster_id_11.0', 'cluster_id_12.0', 'cluster_id_13.0', 'cluster_id_14.0', 'cluster_id_15.0', 'cluster_id_16.0', 'cluster_id_17.0', 'cluster_id_18.0', 'cluster_id_19.0', 'cluster_id_20.0', 'cluster_id_21.0', 'cluster_id_22.0', 'cluster_id_23.0', 'cluster_id_24.0', 'cluster_id_25.0', 'cluster_id_26.0', 'cluster_id_27.0', 'cluster_id_28.0', 'cluster_id_29.0', 'cluster_id_30.0', 'cluster_id_31.0', 'cluster_id_32.0', 'cluster_id_33.0', 'cluster_id_34.0', 'cluster_id_35.0', 'cluster_id_36.0', 'cluster_id_37.0', 'cluster_id_38.0', 'cluster_id_39.0', 'cluster_id_40.0', 'cluster_id_41.0', 'cluster_id_42.0', 'cluster_id_43.0', 'cluster_id_44.0', 'cluster_id_45.0', 'cluster_id_46.0', 'cluster_id_47.0', 'cluster_id_48.0', 'cluster_id_49.0', 'cluster_id_50.0', 'cluster_id_51.0', 'cluster_id_52.0', 'cluster_id_53.0', 'cluster_id_54.0', 'cluster_id_55.0', 'cluster_id_56.0', 'cluster_id_57.0', 'cluster_id_58.0', 'cluster_id_59.0', 'cluster_id_60.0', 'cluster_id_61.0', 'cluster_id_62.0', 'cluster_id_63.0', 'cluster_id_64.0', 'cluster_id_65.0', 'cluster_id_66.0', 'cluster_id_67.0', 'cluster_id_68.0', 'cluster_id_69.0', 'cluster_id_70.0', 'cluster_id_71.0', 'cluster_id_72.0', 'cluster_id_73.0', 'cluster_id_74.0', 'cluster_id_75.0', 'cluster_id_76.0', 'cluster_id_77.0', 'cluster_id_78.0', 'cluster_id_79.0', 'cluster_id_80.0', 'cluster_id_81.0', 'cluster_id_82.0', 'cluster_id_83.0', 'cluster_id_84.0', 'cluster_id_85.0', 'cluster_id_86.0', 'cluster_id_87.0', 'cluster_id_88.0', 'cluster_id_89.0', 'cluster_id_90.0', 'cluster_id_91.0', 'cluster_id_92.0', 'cluster_id_93.0', 'cluster_id_94.0', 'cluster_id_95.0', 'cluster_id_96.0', 'cluster_id_97.0', 'cluster_id_98.0', 'cluster_id_99.0', 'cluster_id_100.0', 'cluster_id_101.0', 'cluster_id_102.0', 'cluster_id_103.0', 'cluster_id_104.0', 'cluster_id_105.0', 'cluster_id_106.0', 'cluster_id_107.0', 'cluster_id_108.0', 'cluster_id_109.0', 'cluster_id_110.0', 'cluster_id_111.0', 'cluster_id_112.0', 'cluster_id_113.0', 'cluster_id_114.0', 'cluster_id_115.0', 'cluster_id_116.0', 'cluster_id_117.0', 'cluster_id_118.0', 'cluster_id_119.0', 'cluster_id_120.0', 'cluster_id_121.0', 'cluster_id_122.0', 'cluster_id_123.0', 'cluster_id_124.0', 'cluster_id_125.0']

In [9]:
%%time
# We will prepare the aggregation dictionary for the various columns

agg_dict = {}

for col in cols_to_keep_first:
    agg_dict[col] = 'first'

for col in cols_to_sum_up:
    agg_dict[col] = np.sum

print(agg_dict)
del col, cols_to_keep_first, cols_to_sum_up

{'gender': 'first', 'age': 'first', 'avg_events': 'first', 'train_test_flag': 'first', 'phone_brand_Coolpad': 'first', 'phone_brand_Gionee': 'first', 'phone_brand_HTC': 'first', 'phone_brand_Huawei': 'first', 'phone_brand_LG': 'first', 'phone_brand_Meizu': 'first', 'phone_brand_OPPO': 'first', 'phone_brand_Sony': 'first', 'phone_brand_TCL': 'first', 'phone_brand_Xiaomi': 'first', 'phone_brand_ZTE': 'first', 'phone_brand_ccmc': 'first', 'phone_brand_dowe': 'first', 'phone_brand_hisense': 'first', 'phone_brand_lenovo': 'first', 'phone_brand_lshi': 'first', 'phone_brand_nubia': 'first', 'phone_brand_others': 'first', 'phone_brand_samsung': 'first', 'phone_brand_vivo': 'first', 'phone_brand_youmi': 'first', 'device_model_1105': 'first', 'device_model_1107': 'first', 'device_model_2': 'first', 'device_model_2016GalAxyA7': 'first', 'device_model_2016GalAxyA9': 'first', 'device_model_3': 'first', 'device_model_3007': 'first', 'device_model_45rggt2': 'first', 'device_model_5263': 'first', 'device_model_5890': 'first', 'device_model_5891': 'first', 'device_model_5891Q': 'first', 'device_model_5892': 'first', 'device_model_5950': 'first', 'device_model_5951': 'first', 'device_model_6607': 'first', 'device_model_7269': 'first', 'device_model_7270': 'first', 'device_model_7295': 'first', 'device_model_7295+': 'first', 'device_model_7295A123': 'first', 'device_model_7295C': 'first', 'device_model_7296': 'first', 'device_model_7620l': 'first', 'device_model_795+': 'first', 'device_model_8017-T00': 'first', 'device_model_802w': 'first', 'device_model_8085': 'first', 'device_model_8089': 'first', 'device_model_8190Q': 'first', 'device_model_8198T': 'first', 'device_model_8702': 'first', 'device_model_8705': 'first', 'device_model_8712': 'first', 'device_model_8720': 'first', 'device_model_8720L': 'first', 'device_model_8729': 'first', 'device_model_8730L': 'first', 'device_model_900tr2': 'first', 'device_model_900tr212': 'first', 'device_model_900tr2123': 'first', 'device_model_9180': 'first', 'device_model_9190l': 'first', 'device_model_9976A': 'first', 'device_model_:UOOGOUT1': 'first', 'device_model_A1': 'first', 'device_model_A11': 'first', 'device_model_A199': 'first', 'device_model_A2800d': 'first', 'device_model_A3000-H': 'first', 'device_model_A31': 'first', 'device_model_A320t': 'first', 'device_model_A33': 'first', 'device_model_A355e': 'first', 'device_model_A360t': 'first', 'device_model_A3800d': 'first', 'device_model_A388t': 'first', 'device_model_A3900': 'first', 'device_model_A390t': 'first', 'device_model_A51': 'first', 'device_model_A53': 'first', 'device_model_A5800-D': 'first', 'device_model_A628t': 'first', 'device_model_A630t': 'first', 'device_model_A670t': 'first', 'device_model_A680': 'first', 'device_model_A708t': 'first', 'device_model_A788t': 'first', 'device_model_A789': 'first', 'device_model_A800': 'first', 'device_model_A820': 'first', 'device_model_A820t': 'first', 'device_model_A830': 'first', 'device_model_A850': 'first', 'device_model_A858t': 'first', 'device_model_A880': 'first', 'device_model_A890e': 'first', 'device_model_Ascend G6': 'first', 'device_model_Ascend G7': 'first', 'device_model_Ascend G700': 'first', 'device_model_Ascend G700T': 'first', 'device_model_Ascend GX1': 'first', 'device_model_Ascend P6': 'first', 'device_model_Ascend P7': 'first', 'device_model_Ascend P8': 'first', 'device_model_B199': 'first', 'device_model_B9388': 'first', 'device_model_Butterfly': 'first', 'device_model_C8813': 'first', 'device_model_C8813Q': 'first', 'device_model_C8815': 'first', 'device_model_C8816': 'first', 'device_model_C8816D': 'first', 'device_model_C8817E': 'first', 'device_model_C8818': 'first', 'device_model_Desire 626': 'first', 'device_model_Desire 816': 'first', 'device_model_Desire 820': 'first', 'device_model_Desire 826': 'first', 'device_model_E3': 'first', 'device_model_E5': 'first', 'device_model_E6': 'first', 'device_model_E7': 'first', 'device_model_ELIFE E3T': 'first', 'device_model_ELIFE S5.5': 'first', 'device_model_F103': 'first', 'device_model_F2': 'first', 'device_model_F301': 'first', 'device_model_F303': 'first', 'device_model_Find 5': 'first', 'device_model_Find 7': 'first', 'device_model_G11': 'first', 'device_model_G2': 'first', 'device_model_G3': 'first', 'device_model_G3588V': 'first', 'device_model_G3818': 'first', 'device_model_G510': 'first', 'device_model_G520-0000': 'first', 'device_model_G520-5000': 'first', 'device_model_G520-T10': 'first', 'device_model_G6-C00': 'first', 'device_model_G6-U00': 'first', 'device_model_G606': 'first', 'device_model_G610C': 'first', 'device_model_G610S': 'first', 'device_model_G610T': 'first', 'device_model_G620-L75': 'first', 'device_model_G628': 'first', 'device_model_G660-L075': 'first', 'device_model_G7 Plus': 'first', 'device_model_G716': 'first', 'device_model_G718C': 'first', 'device_model_G7200': 'first', 'device_model_G730-T00': 'first', 'device_model_G730-U00': 'first', 'device_model_G750-T20': 'first', 'device_model_GN137': 'first', 'device_model_GN151': 'first', 'device_model_GN706L': 'first', 'device_model_GN708W': 'first', 'device_model_GN9002': 'first', 'device_model_Galaxy A3': 'first', 'device_model_Galaxy A5': 'first', 'device_model_Galaxy A7': 'first', 'device_model_Galaxy A8': 'first', 'device_model_Galaxy Ace': 'first', 'device_model_Galaxy Ace 2': 'first', 'device_model_Galaxy Ace 3': 'first', 'device_model_Galaxy Core 2': 'first', 'device_model_Galaxy Core 4G': 'first', 'device_model_Galaxy Core Max': 'first', 'device_model_Galaxy Core Mini': 'first', 'device_model_Galaxy Core Prime': 'first', 'device_model_Galaxy E7': 'first', 'device_model_Galaxy Fame': 'first', 'device_model_Galaxy Grand': 'first', 'device_model_Galaxy Grand 2': 'first', 'device_model_Galaxy Grand DUOS': 'first', 'device_model_Galaxy Grand Neo Plus': 'first', 'device_model_Galaxy Grand Prime': 'first', 'device_model_Galaxy J3': 'first', 'device_model_Galaxy J5': 'first', 'device_model_Galaxy J7': 'first', 'device_model_Galaxy Mega 2': 'first', 'device_model_Galaxy Mega 5.8': 'first', 'device_model_Galaxy Mega 6.3': 'first', 'device_model_Galaxy Mega Plus': 'first', 'device_model_Galaxy Nexus': 'first', 'device_model_Galaxy Note': 'first', 'device_model_Galaxy Note 2': 'first', 'device_model_Galaxy Note 3': 'first', 'device_model_Galaxy Note 3 Lite': 'first', 'device_model_Galaxy Note 4': 'first', 'device_model_Galaxy Note 5': 'first', 'device_model_Galaxy Note 8.0': 'first', 'device_model_Galaxy Note Edge': 'first', 'device_model_Galaxy On5': 'first', 'device_model_Galaxy On7': 'first', 'device_model_Galaxy Premier': 'first', 'device_model_Galaxy S2': 'first', 'device_model_Galaxy S2 HD LTE E120S': 'first', 'device_model_Galaxy S2 Plus': 'first', 'device_model_Galaxy S3': 'first', 'device_model_Galaxy S3 Neo+': 'first', 'device_model_Galaxy S4': 'first', 'device_model_Galaxy S4 Zoom': 'first', 'device_model_Galaxy S5': 'first', 'device_model_Galaxy S6': 'first', 'device_model_Galaxy S6 Edge': 'first', 'device_model_Galaxy S6 Edge+': 'first', 'device_model_Galaxy Style DUOS': 'first', 'device_model_Galaxy Tab 2 P3100': 'first', 'device_model_Galaxy Tab 3 10.1': 'first', 'device_model_Galaxy Tab 3 7.0': 'first', 'device_model_Galaxy Tab 3 8.0': 'first', 'device_model_Galaxy Trend 2': 'first', 'device_model_Galaxy Trend 3': 'first', 'device_model_Galaxy Trend DUOS': 'first', 'device_model_Galaxy Trend DUOS 2': 'first', 'device_model_Galaxy Win': 'first', 'device_model_Galaxy Win Pro': 'first', 'device_model_Grand Memo 2': 'first', 'device_model_Grand S 2': 'first', 'device_model_Grand X Quad': 'first', 'device_model_HN3-U01': 'first', 'device_model_HT-I860': 'first', 'device_model_I8268': 'first', 'device_model_I9118': 'first', 'device_model_K1': 'first', 'device_model_K860i': 'first', 'device_model_K900': 'first', 'device_model_L1 mini': 'first', 'device_model_M032': 'first', 'device_model_M2': 'first', 'device_model_M20-T': 'first', 'device_model_M310': 'first', 'device_model_M4': 'first', 'device_model_M5': 'first', 'device_model_M811': 'first', 'device_model_M812C': 'first', 'device_model_M8St': 'first', 'device_model_MI 1S': 'first', 'device_model_MI 2': 'first', 'device_model_MI 2A': 'first', 'device_model_MI 2C': 'first', 'device_model_MI 2S': 'first', 'device_model_MI 3': 'first', 'device_model_MI 4': 'first', 'device_model_MI 5': 'first', 'device_model_MI One C1': 'first', 'device_model_MI One Plus': 'first', 'device_model_MI pad': 'first', 'device_model_MT1-U06': 'first', 'device_model_MT2-C00': 'first', 'device_model_MX2': 'first', 'device_model_MX3': 'first', 'device_model_MX4': 'first', 'device_model_MX4 Pro': 'first', 'device_model_MX5': 'first', 'device_model_Mate': 'first', 'device_model_Mate 2': 'first', 'device_model_Mate 7': 'first', 'device_model_Mate 8': 'first', 'device_model_Mate S': 'first', 'device_model_Moto G': 'first', 'device_model_Moto X': 'first', 'device_model_N1': 'first', 'device_model_N1 Mini': 'first', 'device_model_N1T': 'first', 'device_model_N3': 'first', 'device_model_Nexus 4': 'first', 'device_model_Nexus 5': 'first', 'device_model_One': 'first', 'device_model_One E8': 'first', 'device_model_One M8': 'first', 'device_model_One X': 'first', 'device_model_One max': 'first', 'device_model_Optimus G Pro': 'first', 'device_model_P301M': 'first', 'device_model_P6': 'first', 'device_model_P70': 'first', 'device_model_P770': 'first', 'device_model_P8 Lite': 'first', 'device_model_P880': 'first', 'device_model_P8max': 'first', 'device_model_PRO5': 'first', 'device_model_Q505T': 'first', 'device_model_Q802T': 'first', 'device_model_R1': 'first', 'device_model_R1C': 'first', 'device_model_R1S': 'first', 'device_model_R2017': 'first', 'device_model_R3': 'first', 'device_model_R5': 'first', 'device_model_R6007': 'first', 'device_model_R7': 'first', 'device_model_R7 Plus': 'first', 'device_model_R7s': 'first', 'device_model_R809T': 'first', 'device_model_R811': 'first', 'device_model_R813T': 'first', 'device_model_R815T': 'first', 'device_model_R817T': 'first', 'device_model_R819T': 'first', 'device_model_R8205': 'first', 'device_model_R821T': 'first', 'device_model_R823T': 'first', 'device_model_R827T': 'first', 'device_model_R830': 'first', 'device_model_R831S': 'first', 'device_model_R831T': 'first', 'device_model_R833T': 'first', 'device_model_S2y': 'first', 'device_model_S3': 'first', 'device_model_S5.1': 'first', 'device_model_S5.5L': 'first', 'device_model_S5830I': 'first', 'device_model_S6': 'first', 'device_model_S658t': 'first', 'device_model_S7': 'first', 'device_model_S720': 'first', 'device_model_S7568': 'first', 'device_model_S7568I': 'first', 'device_model_S7898': 'first', 'device_model_S7I': 'first', 'device_model_S7T': 'first', 'device_model_S810t': 'first', 'device_model_S820': 'first', 'device_model_S850t': 'first', 'device_model_S868t': 'first', 'device_model_S890': 'first', 'device_model_S898t': 'first', 'device_model_S9': 'first', 'device_model_S90-t': 'first', 'device_model_S920': 'first', 'device_model_T1': 'first', 'device_model_T329t': 'first', 'device_model_Talkv2': 'first', 'device_model_Touch 2': 'first', 'device_model_Touch 3': 'first', 'device_model_Two': 'first', 'device_model_U3': 'first', 'device_model_U51GT-W': 'first', 'device_model_U705T': 'first', 'device_model_U707T': 'first', 'device_model_U807': 'first', 'device_model_U817': 'first', 'device_model_U9508': 'first', 'device_model_U956': 'first', 'device_model_UIMI3': 'first', 'device_model_UIMI4': 'first', 'device_model_V182': 'first', 'device_model_V185': 'first', 'device_model_V5 Max': 'first', 'device_model_V5S': 'first', 'device_model_V967S': 'first', 'device_model_VIBE X2': 'first', 'device_model_VIBE Z': 'first', 'device_model_W2013': 'first', 'device_model_W2014': 'first', 'device_model_W2015': 'first', 'device_model_X1': 'first', 'device_model_X1 7.0': 'first', 'device_model_X1ST': 'first', 'device_model_X3L': 'first', 'device_model_X3S': 'first', 'device_model_X3T': 'first', 'device_model_X3V': 'first', 'device_model_X5L': 'first', 'device_model_X5M': 'first', 'device_model_X5Max': 'first', 'device_model_X5Max+': 'first', 'device_model_X5Pro': 'first', 'device_model_X5SL': 'first', 'device_model_X5V': 'first', 'device_model_X6': 'first', 'device_model_X6 D': 'first', 'device_model_X6 L': 'first', 'device_model_X6 Plus': 'first', 'device_model_X6 Plus D': 'first', 'device_model_X710L': 'first', 'device_model_X805': 'first', 'device_model_X907': 'first', 'device_model_XL': 'first', 'device_model_Xperia C': 'first', 'device_model_Xperia C3': 'first', 'device_model_Xperia P': 'first', 'device_model_Xperia S': 'first', 'device_model_Xperia SL': 'first', 'device_model_Xperia SP': 'first', 'device_model_Xperia T2 Ultra': 'first', 'device_model_Xperia TX': 'first', 'device_model_Xperia Z': 'first', 'device_model_Xperia Z Ultra': 'first', 'device_model_Xperia Z1': 'first', 'device_model_Xperia Z2': 'first', 'device_model_Xperia Z3': 'first', 'device_model_Xperia arc S': 'first', 'device_model_Xplay': 'first', 'device_model_Xplay3S': 'first', 'device_model_Y11': 'first', 'device_model_Y11IT': 'first', 'device_model_Y11IW': 'first', 'device_model_Y13': 'first', 'device_model_Y13L': 'first', 'device_model_Y13iL': 'first', 'device_model_Y15': 'first', 'device_model_Y17T': 'first', 'device_model_Y17W': 'first', 'device_model_Y18L': 'first', 'device_model_Y19T': 'first', 'device_model_Y20T': 'first', 'device_model_Y22': 'first', 'device_model_Y22IL': 'first', 'device_model_Y22L': 'first', 'device_model_Y23L': 'first', 'device_model_Y27': 'first', 'device_model_Y28L': 'first', 'device_model_Y29L': 'first', 'device_model_Y300': 'first', 'device_model_Y33': 'first', 'device_model_Y35': 'first', 'device_model_Y37': 'first', 'device_model_Y51': 'first', 'device_model_Y511-T00': 'first', 'device_model_Y511-U00': 'first', 'device_model_Y516': 'first', 'device_model_Y600-U00': 'first', 'device_model_Y613': 'first', 'device_model_Y635': 'first', 'device_model_Y635-TL00': 'first', 'device_model_Y80D': 'first', 'device_model_Y913': 'first', 'device_model_Y923': 'first', 'device_model_Y927': 'first', 'device_model_Z1': 'first', 'device_model_Z5S': 'first', 'device_model_Z5S Mini': 'first', 'device_model_Z7 Max': 'first', 'device_model_Z7 Mini': 'first', 'device_model_Z9': 'first', 'device_model_Z9 Max': 'first', 'device_model_Z9 mini': 'first', 'device_model_ZenFone 2': 'first', 'device_model_a1900tr212': 'first', 'device_model_bigv23': 'first', 'device_model_cv1': 'first', 'device_model_cv1plus': 'first', 'device_model_hu1': 'first', 'device_model_hu1 Plus': 'first', 'device_model_hu1 plus': 'first', 'device_model_iPh-800': 'first', 'device_model_iSuper S1': 'first', 'device_model_ihv1': 'first', 'device_model_ivvi K1 mini': 'first', 'device_model_ivvi å°\x8fi': 'first', 'device_model_mate7es2': 'first', 'device_model_menote1': 'first', 'device_model_menote1 2': 'first', 'device_model_notev123': 'first', 'device_model_others': 'first', 'device_model_x1': 'first', 'device_model_x11S': 'first', 'device_model_x12': 'first', 'device_model_x12A': 'first', 'device_model_x13': 'first', 'device_model_xnote': 'first', 'device_model_xnote11': 'first', 'device_model_xnote2': 'first', 'device_model_xnote3': 'first', 'device_model_xnotea11': 'first', 'device_model_zt_121': 'first', 'device_model_ä¹\x90æª¬K3': 'first', 'device_model_ä¹\x90æª¬K3 Note': 'first', 'device_model_ä¹ˆä¹ˆå“’': 'first', 'device_model_ä¹ˆä¹ˆå“’3N': 'first', 'device_model_å\x9dšæžœæ‰‹æœº': 'first', 'device_model_å°\x8fç±³4C': 'first', 'device_model_å°\x8fè¾£æ¤’ M2': 'first', 'device_model_å°\x8fè‹¹æžœ': 'first', 'device_model_æ˜¥é›·HD': 'first', 'device_model_æ˜Ÿæ˜Ÿ1å\x8f·': 'first', 'device_model_æ——èˆ°ç‰ˆ': 'first', 'device_model_ç\x81«æ˜Ÿä¸€å\x8f·': 'first', 'device_model_çº¢è¾£æ¤’': 'first', 'device_model_çº¢è¾£æ¤’Note': 'first', 'device_model_çº½æ‰£': 'first', 'device_model_ç‚«å½±S+': 'first', 'device_model_ç•…äº«5': 'first', 'device_model_ç•…äº«5S': 'first', 'device_model_è\x81”æƒ³é»„é‡‘æ–—å£«S8': 'first', 'device_model_è\x8d£è€€+': 'first', 'device_model_è\x8d£è€€3C': 'first', 'device_model_è\x8d£è€€3Cç•…çŽ©ç‰ˆ': 'first', 'device_model_è\x8d£è€€3X': 'first', 'device_model_è\x8d£è€€3Xç•…çŽ©ç‰ˆ': 'first', 'device_model_è\x8d£è€€4A': 'first', 'device_model_è\x8d£è€€7': 'first', 'device_model_è\x8d£è€€7i': 'first', 'device_model_è\x8d£è€€X2': 'first', 'device_model_è\x8d£è€€ç•…çŽ©4': 'first', 'device_model_è\x8d£è€€ç•…çŽ©4C': 'first', 'device_model_è\x8d£è€€ç•…çŽ©4Cè¿\x90åŠ¨ç‰ˆ': 'first', 'device_model_è\x8d£è€€ç•…çŽ©4X': 'first', 'device_model_è\x8d£è€€ç•…çŽ©5': 'first', 'device_model_è\x8d£è€€ç•…çŽ©5X': 'first', 'device_model_è¶…çº§æ‰‹æœº1': 'first', 'device_model_è¶…çº§æ‰‹æœº1 Pro': 'first', 'device_model_è¶…çº§æ‰‹æœºMax': 'first', 'device_model_é\x9d’æ˜¥ç‰ˆ': 'first', 'device_model_é\xad…è“\x9d': 'first', 'device_model_é\xad…è“\x9d2': 'first', 'device_model_é\xad…è“\x9dmetal': 'first', 'device_model_éº¦èŠ’3': 'first', 'device_model_éº¦èŠ’3S': 'first', 'device_model_éº¦èŠ’4': 'first', 'device_model_é»„é‡‘æ–—å£«A8': 'first', 'device_model_é»„é‡‘æ–—å£«Note8': 'first', 'device_model_é”‹å°š': 'first', 'device_model_é”‹å°šPro': 'first', 'device_model_é‡‘é’¢': 'first', 'is_active': <function sum at 0x000002466E1D4F78>, 'gaming': <function sum at 0x000002466E1D4F78>, 'financial': <function sum at 0x000002466E1D4F78>, 'travel': <function sum at 0x000002466E1D4F78>, 'technology': <function sum at 0x000002466E1D4F78>, 'family': <function sum at 0x000002466E1D4F78>, 'children': <function sum at 0x000002466E1D4F78>, 'education': <function sum at 0x000002466E1D4F78>, 'lifestyle': <function sum at 0x000002466E1D4F78>, 'social': <function sum at 0x000002466E1D4F78>, 'services': <function sum at 0x000002466E1D4F78>, 'others': <function sum at 0x000002466E1D4F78>, 'hour_0.0': <function sum at 0x000002466E1D4F78>, 'hour_1.0': <function sum at 0x000002466E1D4F78>, 'hour_2.0': <function sum at 0x000002466E1D4F78>, 'hour_3.0': <function sum at 0x000002466E1D4F78>, 'hour_4.0': <function sum at 0x000002466E1D4F78>, 'hour_5.0': <function sum at 0x000002466E1D4F78>, 'hour_6.0': <function sum at 0x000002466E1D4F78>, 'hour_7.0': <function sum at 0x000002466E1D4F78>, 'hour_8.0': <function sum at 0x000002466E1D4F78>, 'hour_9.0': <function sum at 0x000002466E1D4F78>, 'hour_10.0': <function sum at 0x000002466E1D4F78>, 'hour_11.0': <function sum at 0x000002466E1D4F78>, 'hour_12.0': <function sum at 0x000002466E1D4F78>, 'hour_13.0': <function sum at 0x000002466E1D4F78>, 'hour_14.0': <function sum at 0x000002466E1D4F78>, 'hour_15.0': <function sum at 0x000002466E1D4F78>, 'hour_16.0': <function sum at 0x000002466E1D4F78>, 'hour_17.0': <function sum at 0x000002466E1D4F78>, 'hour_18.0': <function sum at 0x000002466E1D4F78>, 'hour_19.0': <function sum at 0x000002466E1D4F78>, 'hour_20.0': <function sum at 0x000002466E1D4F78>, 'hour_21.0': <function sum at 0x000002466E1D4F78>, 'hour_22.0': <function sum at 0x000002466E1D4F78>, 'hour_23.0': <function sum at 0x000002466E1D4F78>, 'dayofweek_1-Mon': <function sum at 0x000002466E1D4F78>, 'dayofweek_2-Tue': <function sum at 0x000002466E1D4F78>, 'dayofweek_3-Wed': <function sum at 0x000002466E1D4F78>, 'dayofweek_4-Thu': <function sum at 0x000002466E1D4F78>, 'dayofweek_5-Fri': <function sum at 0x000002466E1D4F78>, 'dayofweek_6-Sat': <function sum at 0x000002466E1D4F78>, 'dayofweek_7-Sun': <function sum at 0x000002466E1D4F78>, 'cluster_id_-1.0': <function sum at 0x000002466E1D4F78>, 'cluster_id_0.0': <function sum at 0x000002466E1D4F78>, 'cluster_id_1.0': <function sum at 0x000002466E1D4F78>, 'cluster_id_2.0': <function sum at 0x000002466E1D4F78>, 'cluster_id_3.0': <function sum at 0x000002466E1D4F78>, 'cluster_id_4.0': <function sum at 0x000002466E1D4F78>, 'cluster_id_5.0': <function sum at 0x000002466E1D4F78>, 'cluster_id_6.0': <function sum at 0x000002466E1D4F78>, 'cluster_id_7.0': <function sum at 0x000002466E1D4F78>, 'cluster_id_8.0': <function sum at 0x000002466E1D4F

In [10]:
%%time
# We will aggregate the keep_first and sum_up columns over groupby 'device_id' column

df_scn1 = df_scn1.drop(columns=['event_id']).groupby('device_id').agg(agg_dict).reset_index()
display(df_scn1)
df_scn1.info()
del agg_dict

,device_id,gender,age,avg_events,train_test_flag,phone_brand_Coolpad,phone_brand_Gionee,phone_brand_HTC,phone_brand_Huawei,phone_brand_LG,...,cluster_id_116.0,cluster_id_117.0,cluster_id_118.0,cluster_id_119.0,cluster_id_120.0,cluster_id_121.0,cluster_id_122.0,cluster_id_123.0,cluster_id_124.0,cluster_id_125.0
0,-1001337759327040000,1,1,109,train,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,-1002733576670970000,1,2,55,train,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,-1005411102947240000,1,2,44,train,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,-1006357788560220000,1,2,51,train,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,-1010331399860270000,1,1,4,train,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11203,990879148135067000,0,1,4,train,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11204,992109739203134000,0,2,251,train,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11205,998208026013018000,0,1,71,train,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11206,998402647311351000,1,0,4,train,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
11207,999208698621622000,1,1,37,train,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11208 entries, 0 to 11207
Columns: 697 entries, device_id to cluster_id_125.0
dtypes: float64(36), int64(3), object(2), uint8(656)
memory usage: 10.5+ MB
Wall time: 10.3 s

In [11]:
%%time
# Finally we will persist the Scenario1 dataset to local storage for retrieval and processing in subsequent tasks

df_scn1.to_csv('df_scn1.csv', header=True, index=False)
del df_scn1

Wall time: 2.42 s

#### Scenario 2 - Only mobile phone, brand and device data available

In [12]:
%%time
# We will separate out the scenario 2 data from the master dataset

df_scn2 = df_master[df_master.event_id.isna()].copy().dropna(axis=1).drop(columns=['avg_events']).reset_index(drop=True)
display(df_scn2)
df_scn2.info()

,device_id,gender,age,train_test_flag,phone_brand_Coolpad,phone_brand_Gionee,phone_brand_HTC,phone_brand_Huawei,phone_brand_LG,phone_brand_Meizu,...,device_model_é­…è“2,device_model_é­…è“metal,device_model_éº¦èŠ’3,device_model_éº¦èŠ’3S,device_model_éº¦èŠ’4,device_model_é»„é‡‘æ–—å£«A8,device_model_é»„é‡‘æ–—å£«Note8,device_model_é”‹å°š,device_model_é”‹å°šPro,device_model_é‡‘é’¢
0,-1000369272589010000,0,1,test,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,-1000572055892390000,0,1,train,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,-1000643208750510000,1,1,train,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,-1001949518704260000,1,0,train,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,-1002079624347530000,0,2,train,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51330,998997036709813000,0,1,train,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
51331,999356919477646000,1,1,test,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
51332,999529955917823000,0,0,train,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51333,999861742187156000,1,1,train,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51334,999942881634637000,0,1,train,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51335 entries, 0 to 51334
Columns: 526 entries, device_id to device_model_é‡‘é’¢
dtypes: category(3), object(1), uint8(522)
memory usage: 26.1+ MB
Wall time: 465 ms

In [13]:
%%time
# Finally we will persist the Scenario2 dataset to local storage for retrieval and processing in subsequent tasks

df_scn2.to_csv('df_scn2.csv', header=True, index=False)
del df_master, df_scn2

Wall time: 4.44 s

___With this we have reached the end of the Scenario1 & Scenario2 Data Segmentation stage. Model Building for Scenario1 & Scenario2 will be taken up in the subsequent stages.___